<a href="https://colab.research.google.com/github/MinhQuann205/TH-DeepLearning/blob/main/BaiThucHanhBuoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
  import numpy as np
print("NUMPY")
# cach1
my_list=[1,2,3,4,5]
print("python list", my_list)
my_numpy_array=np.array(my_list)
print("my numpy array",my_numpy_array)
#cach2
a=np.array([1,2,3,4,56])
print(a)
print("\n")


#array 2 chieu
array_2=np.array([(1,2,3),(4,5,6)])
print("mang 2 chieu",array_2)
print("\n")


#array 3 chieu
print("mang 3 chieu")
array_3=np.array([
    [[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("mang 3 chieu",array_3)
print(array_3.shape)
print("\n")

#array voi gia tri ban dau la 0 voi 1
print("mang cac so 0 voi 1 ")
array_zero=np.zeros((2,2))
array_ones=np.ones((2,2))
print("mang cac so 0",array_zero)
print("mang cac so 1",array_ones)
print("\n")

#reshape
print("reshape ")
array_4=np.array([[1,2,3],[4,5,6]])
print(array_4)
print("shape",array_4.shape)
print("\n")
print("reshape",array_4.reshape(3,2))
print("\n")

array_5=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_5)
print("shape array 5",array_5.shape)
array_6=array_5.reshape(3,4)
print("shape array 6 after reshape",array_6.shape)
array_7=array_5.reshape(2,3,2)
print("shape array 7 after reshape",array_7.shape)
print("array 7", array_7)
print("\n")

#flatten
print("flatten")
array_flatten=array_7.flatten()
print("array flatten",array_flatten)
print("\n")

#them dong voi du lieu voi hstack(ngang) va vstack(doc)
print("them dong voi du lieu voi hstack(ngang) va vstack(doc)")
f=np.array([1,2,3])
g=np.array([4,5,6])
h_stack=np.hstack((f,g))
print("h stack",h_stack)
v_stack=np.vstack((f,g))
print("v stack",v_stack)
print("\n")

#Sinh mang so nguyen ngau nhien
print("sinh mang voi so nguyen ngau nhien")
a=np.random.randint(100,size=5)
print("random 1D",a)
print("\n")
b=np.random.randint(100,size=(2,3))
print("random 2D",b)
print("\n")
c=np.random.randint(100,size=(2,3,2))
print("random 3D",c)
print("\n")

#Sinh mang ngau nhien so thuc trong khoang [0,1]
print("sinh mang ngau nhien so thuc trong khoang [0,1]")
random1=np.random.rand(5)
print(random1)
print("\n")
random2=np.random.rand(2,3)
print(random2)
print("\n")
random3=np.random.rand(2,3,2)
print(random3)
print("\n")


#Sinh mang so ngau nhien theo phan phoi chuan Gaussian
print("Sinh mang so ngau nhien theo phan phoi chuan Gaussian")
#np.random.normal(loc,scale,size) loc:gia tri trung tap, scale:do lech chuan , size:so phan tu tra ve
random_gaussian=np.random.normal(5,0.5,10)
print("\n")

#Sinh 1 gia tri ngau nhien tu mang gia tri cho truoc
print("Sinh 1 gia tri ngau nhien tu mang cho truoc")
random_choice=np.random.choice([3,5,7,9])
print(random_choice)
print("Sinh ma tran ngau nhien tu gia tri cho truoc")
random_choice_array=np.random.choice([1,3,5,7,9,11],size=(3,3))
print(random_choice_array)
print("\n")


#Thay doi gia tri cua ma tran
array_change=np.matrix(np.ones((5,5)))
print("ma tran A",array_change)
np.array(array_change)[2]=2
print("thay doi gia tri cot thu 3 voi array",array_change)
np.asarray(array_change)[2]=2
print("thay doi gia tri cot thu 3 voi asarray",array_change)
print("\n")

#Sinh day so theo khoang cho truoc
listDigit=np.arange(1,20)
print(listDigit)
print("tao 20 so voi moi buoc la 2")
listDigit2=np.arange(1,20,2)
print(listDigit2)
print("\n")

#linspace
listDigitLinspace=np.linspace(1,20,5)
print(listDigitLinspace)
print("\n")

#index va slice
print("slice")
array_8=np.array([[1,2,3,4],[5,6,7,8]])
print(array_8)
print("first row: ", array_8[0])
print("second row: ", array_8[1])
print("index")
print("first column",array_8[:,0])
print("second column",array_8[:,1])

NUMPY
python list [1, 2, 3, 4, 5]
my numpy array [1 2 3 4 5]
[ 1  2  3  4 56]


mang 2 chieu [[1 2 3]
 [4 5 6]]


mang 3 chieu
mang 3 chieu [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


mang cac so 0 voi 1 
mang cac so 0 [[0. 0.]
 [0. 0.]]
mang cac so 1 [[1. 1.]
 [1. 1.]]


reshape 
[[1 2 3]
 [4 5 6]]
shape (2, 3)


reshape [[1 2]
 [3 4]
 [5 6]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
shape array 5 (2, 2, 3)
shape array 6 after reshape (3, 4)
shape array 7 after reshape (2, 3, 2)
array 7 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


flatten
array flatten [ 1  2  3  4  5  6  7  8  9 10 11 12]


them dong voi du lieu voi hstack(ngang) va vstack(doc)
h stack [1 2 3 4 5 6]
v stack [[1 2 3]
 [4 5 6]]


sinh mang voi so nguyen ngau nhien
random 1D [ 2 42 65  4 87]


random 2D [[28 55  6]
 [92 39  7]]


random 3D [[[58 11]
  [94 55]
  [77 87]]

 [[ 4 63]
  [35 72]
  [ 2 73]]]


sinh mang ngau nhien so thuc trong khoang [0,1]
[0.84705