<a href="https://colab.research.google.com/github/MinhQuann205/TH-DeepLearning/blob/main/Selamat_Datang_di_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
my_list = [1,9,15,39]
print('Python list: ',my_list)
my_numpy_array=np.array(my_list)
print('Numpy array: ',my_numpy_array)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]


In [9]:
c = np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)


[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [10]:
d =np.array([
              [[1.,2.,3.,],[4.,5.,6.]],
              [[7.,8.,9.],[10,11,12]]
            ])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [12]:
e =np.zeros((2,2))
f=np.ones((3,3))
print('Zero matrix: \n',e)
print('One matrix \n',f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
e=np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
f=e.reshape(3,2)
print(f)
g=np.array([[[1.,2.,3.],[4.,5.,6.]],[[7.,8.,9.],[10.,11.,12.]]])
print(g)
print(g.shape)
h=g.reshape(3,4)
print('reshape (3,4)\n',h)
j=g.reshape(2,3,2)
print('reshape (2,3,2)\n',j)
k=g.reshape(2,2,3)
print('reshape (2,2,3)\n',k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3,4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (2,3,2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]
reshape (2,2,3)
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


In [17]:
e =np.array([[1.,2.,3.],[4.,5.,6.]])
f=e.flatten()
print(f)
g=np.array([[[1.,2.,3.],[4.,5.,6.]],[[7.,8.,9.],[10.,11.,12.]]])
j=g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [19]:
f=np.array([1.,2.,3.])
g=np.array([4.,5.,6.])
h_stack=np.hstack((f,g))
print('Horizontal Append',h_stack)
v_stack =np.vstack((f,g))
print('Vertical Append',v_stack)

Horizontal Append [1. 2. 3. 4. 5. 6.]
Vertical Append [[1. 2. 3.]
 [4. 5. 6.]]


In [25]:
a=np.random.randint(100,size=(5,))
print('Random 1-D array\n',a)
b=np.random.randint(100,size=(3,4))
print('Random 2-d array\n',b)
c=np.random.randint(100,size=(3,4,3))
print('Random 3-D array\n',c)

Random 1-D array
 [70 98 78 18 15]
Random 2-d array
 [[42  8 38 93]
 [30 85 44 86]
 [96 98 46 12]]
Random 3-D array
 [[[36 86 92]
  [65 83 13]
  [99 40 77]
  [47 48  1]]

 [[44 42 30]
  [50 20 79]
  [48 41 40]
  [48 54 55]]

 [[70 58 68]
  [78 69 34]
  [29 87 75]
  [91 59 54]]]


In [26]:
a=np.random.rand(5)
print('Random 1-D array\n',a)
b=np.random.rand(3,4)
print('Random 2-D array\n',b)
c=np.random.rand(3,4,3)
print('Random 3-D array\n',c)

Random 1-D array
 [0.63216304 0.91616955 0.26947805 0.75011449 0.78612654]
Random 2-D array
 [[0.08328144 0.28491055 0.88826749 0.65975162]
 [0.58382477 0.74710971 0.54491992 0.88894074]
 [0.51804975 0.83164331 0.31856829 0.70881765]]
Random 3-D array
 [[[0.42026405 0.69724255 0.69614593]
  [0.35797602 0.15508584 0.27964353]
  [0.58953785 0.87169534 0.16755312]
  [0.46028904 0.24385591 0.9028878 ]]

 [[0.71341424 0.76637828 0.94706847]
  [0.14533769 0.22695896 0.38125972]
  [0.93858563 0.57743278 0.18377471]
  [0.45729538 0.19434273 0.47643343]]

 [[0.41068944 0.66871954 0.19344178]
  [0.31216964 0.69866951 0.82260387]
  [0.97949748 0.85310387 0.23885335]
  [0.61366643 0.71720022 0.66389664]]]


In [27]:
a=np.random.normal(5,0.5,10)
print('Random 1-D array\n',a)
print('Min: ',a.min())
print('Max: ',a.max())
print('Mean: ',a.mean())
print('Median: ',np.median(a))

Random 1-D array
 [5.37479267 4.41132969 4.6374284  5.08944078 4.46324073 5.00294879
 5.17389117 4.26752252 5.56506665 4.04315009]
Min:  4.043150085190484
Max:  5.565066648144795
Mean:  4.8028811488066925
Median:  4.8201885958842965


In [35]:
a=np.random.choice([2,4,6,8,10,12,14,16,18,20])
print(a)
b=np.random.choice([2,4,6,8,10,12,14,16,18,20],size=(3,5))
print(b)


16
[[ 6 12 14 12  2]
 [14 12 10 10  2]
 [14 18 18  8  6]]


In [37]:
a=np.arange(1,20)
print(a)
b=np.arange(1,20,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [39]:
a=np.linspace(1.,5.,num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [40]:
a=np.array([(1,2,3),(4,5,6)])
print(a)
print('fisrt row: ',a[0])
print('second row:',a[1])
print('Second column',a[:,1])
print('first column',a[:,0])
print('Fisrt two values of second row:',a[1,:2])

[[1 2 3]
 [4 5 6]]
fisrt row:  [1 2 3]
second row: [4 5 6]
Second column [2 5]
first column [1 4]
Fisrt two values of second row: [4 5]


In [42]:
import pandas as pd
a=pd.Series([1.,2.,3.,])
print(a)
print('Fisrt value: ',a[0])
b=pd.Series([1.,2.,3.],index=['a','b','c'])
print(b)
print('Fisrt value: ',b['a'])
calories={"day1":420,"day2":380,"day3":390}
myvar=pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
Fisrt value:  1.0
a    1.0
b    2.0
c    3.0
dtype: float64
Fisrt value:  1.0
day1    420
day2    380
day3    390
dtype: int64


In [43]:
h=np.array([[1,2],[3,4]])
df_h=pd.DataFrame(h)
print('DataFrame: \n',df_h)
numpy_h=np.array(df_h)
print('Numpy array:\n',numpy_h)


DataFrame: 
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


In [47]:
dic ={'Name':['John','Smith'],'Age':[30,40]}
df_dic=pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [48]:
r=np.random.randn(20,4)
df=pd.DataFrame(r,columns=['so1','so2','so3','so4'])
print(df.head())

        so1       so2       so3       so4
0 -0.054349  0.287433  0.883744 -0.328705
1 -0.335552  1.249153 -1.653035  0.135160
2 -1.960893  1.360919 -1.246198  0.824861
3 -0.349058  0.788813  1.239094  0.947562
4 -0.242310 -0.039766  0.169190 -0.525032


In [50]:
r=np.random.randn(20,4)
df=pd.DataFrame(r,columns=['so1','so2','so3','so4'])
print(df.head())
print('Chọn cột so1\n',df['so1'])
print('Chọn nhiều dòng\n',df[0:3])
print('Chọn nhiều cột\n',df[['so1','so3']])
print('Chọn nhiều dòng,nhiều cột\n',df.iloc[:3,:2])
df=df.drop(columns=['so1','so4'])
print(df)

        so1       so2       so3       so4
0 -0.976173  0.890208  0.989970  0.947297
1  0.565993  0.272665  0.485028  0.455215
2  1.438411 -1.123184  0.614877  0.270874
3 -0.567348 -0.999489  1.215848 -0.004769
4 -2.337367 -0.890560 -0.724543  1.583659
Chọn cột so1
 0    -0.976173
1     0.565993
2     1.438411
3    -0.567348
4    -2.337367
5     0.255167
6     1.716445
7     1.314862
8     0.955752
9     0.553991
10   -0.643151
11   -0.864945
12    0.786020
13   -0.437853
14    0.172892
15    0.700708
16    1.221719
17   -0.494443
18    0.928641
19   -1.038064
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0 -0.976173  0.890208  0.989970  0.947297
1  0.565993  0.272665  0.485028  0.455215
2  1.438411 -1.123184  0.614877  0.270874
Chọn nhiều cột
          so1       so3
0  -0.976173  0.989970
1   0.565993  0.485028
2   1.438411  0.614877
3  -0.567348  1.215848
4  -2.337367 -0.724543
5   0.255167 -0.364537
6   1.716445 -1.068487
7   1.314862 -0.442581


In [53]:
df1=pd.DataFrame({'Name':['John','Smith','Paul'],'Age':[25,30,50]},index=[0,1,2])
df2=pd.DataFrame({'Name':['Adam','Smith'],'Age':[26,11]},index=[3,4])
df_concat=pd.concat([df1,df2])
print('Concate two DataFrame \n',df_concat)
print('Drop duplicatevalues in DatFame\n',df_concat.drop_duplicates('Name'))
print('Sort values in DataFrame\n',df_concat.sort_values('Age'))
df_rename=df_concat.rename(columns={'Name':'Surname','Age':'Age_pupil'})
print('Rename column of DataFrame\n',df_rename)

Concate two DataFrame 
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicatevalues in DatFame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename column of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11
